"""Resolve with pip, retaining hashes without embedding workstation mirror URLs."""

import argparse
from importlib.metadata import version
from pathlib import Path
import re
import subprocess
import sys
import sysconfig
import tempfile
import tomllib


def render_requirements(lock: dict) -> str:
    if lock.get("lock-version") != "1.0" or not lock.get("packages"):
        raise ValueError("Expected a nonempty pip lock-version 1.0 document")
    lines = [
        "# Generated by scripts\\lock_python_dependencies.py; do not edit.",
        "# Target: Windows x64, CPython 3.11. Install with --require-hashes --only-binary=:all:.",
        "",
    ]
    names = set()
    for package in sorted(lock["packages"], key=lambda item: item["name"]):
        name, release = package["name"], package["version"]
        normalized = re.sub(r"[-_.]+", "-", name).lower()
        hashes = sorted({wheel["hashes"]["sha256"] for wheel in package.get("wheels", [])})
        if (not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", name)
                or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.+!_-]*", release)
                or normalized in names or not hashes
                or any(not re.fullmatch(r"[0-9a-f]{64}", digest) for digest in hashes)):
            raise ValueError("Each package must have a unique name, pinned version and valid wheel hashes")
        names.add(normalized)
        lines.append(f"{normalized}=={release} \\")
        lines.extend(f"    --hash=sha256:{digest}" + (" \\" if index + 1 < len(hashes) else "")
                     for index, digest in enumerate(hashes))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--constraint", type=Path, help="Optional constraints when preserving tested versions")
    args = parser.parse_args()
    if (sys.implementation.name != "cpython" or sys.version_info[:2] != (3, 11)
            or sys.platform != "win32" or sysconfig.get_platform() != "win-amd64"):
        raise SystemExit("Generate these locks with Windows x64 CPython 3.11.")
    if version("pip") != "26.2.1":
        raise SystemExit("Lock generation requires pip==26.2.1; installation does not.")
    root = Path(__file__).resolve().parent.parent
    outputs = {}
    with tempfile.TemporaryDirectory(prefix="msguide-python-lock-") as temporary:
        for source, destination in (("requirements.txt", "requirements.lock.txt"),
                                    ("requirements-dev.txt", "requirements-dev.lock.txt")):
            lock_path = Path(temporary) / "pylock.toml"
            command = [sys.executable, "-m", "pip", "lock", "--only-binary=:all:",
                       "--quiet", "-r", str(root / source), "--output", str(lock_path)]
            if args.constraint:
                command.extend(["--constraint", str(args.constraint.resolve(strict=True))])
            subprocess.run(command, cwd=root, check=True)
            with lock_path.open("rb") as stream:
                outputs[destination] = render_requirements(tomllib.load(stream))
    for destination, content in outputs.items():
        (root / destination).write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
